name: ci

on: [push, pull_request]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0            # get full history so gh-pages can detect changes
          persist-credentials: true # allow pushes with GITHUB_TOKEN

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Test with pytest
        run: poetry run pytest SpectralCorr/tests/ --cov=SpectralCorr --cov-report=xml

      - name: Use Codecov to track coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
